import { Router } from 'express';
import authRoutes from './authRoutes';
import userRoutes from './userRoutes';
import photoRoutes from './photoRoutes';
import messageRoutes from './messageRoutes';
import notificationRoutes from './notificationRoutes';
import lifestyleRoutes from './lifestyleRoutes';
import contactRoutes from './contactRoutes';
import configRoutes from './configRoutes';
import paypalRoutes from './paypalRoutes';
import mediaRoutes from './mediaRoutes';
import locationBeaconRoutes from './locationBeaconRoutes';
import splashSurveyRoutes from './splashSurveyRoutes';
import singleRoutes from './singleRoutes';
import adminMonitoringRoutes from './adminMonitoringRoutes';
import adminReengagementRoutes from './adminReengagementRoutes';
import reengagementPreferenceRoutes from './reengagementPreferenceRoutes';
import adminVerificationReminderRoutes from './adminVerificationReminderRoutes';
import verificationPreferenceRoutes from './verificationPreferenceRoutes';
import adminFakeUserRoutes from './adminFakeUserRoutes';
import adminFakeChatRoutes from './adminFakeChatRoutes';
import adminPhotoGalleryRoutes from './adminPhotoGalleryRoutes';
import voiceMessageRoutes from './voiceMessageRoutes';
import aiRoutes from './aiRoutes';

const router = Router();

router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/photos', photoRoutes);
router.use('/messages', messageRoutes);
router.use('/notifications', notificationRoutes);
router.use('/lifestyle', lifestyleRoutes);
router.use('/contact', contactRoutes);
router.use('/config', configRoutes);
router.use('/paypal', paypalRoutes);
router.use('/media', mediaRoutes);
router.use('/voice-messages', voiceMessageRoutes);
router.use('/location-beacons', locationBeaconRoutes);
router.use('/splash', splashSurveyRoutes);
router.use('/singles', singleRoutes);
router.use('/ai', aiRoutes);
router.use('/monitoring', adminMonitoringRoutes);
router.use('/admin/reengagement', adminReengagementRoutes);
router.use('/admin/fake-users', adminFakeUserRoutes);
router.use('/admin/fake-chats', adminFakeChatRoutes);
router.use('/admin/photo-gallery', adminPhotoGalleryRoutes);
router.use('/reengagement/preferences', reengagementPreferenceRoutes);
router.use('/admin/verification-reminders', adminVerificationReminderRoutes);
router.use('/verification/preferences', verificationPreferenceRoutes);

export default router;
